services:
  app:
    image: cognitia-backend:latest
    container_name: cognitia-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    mem_limit: 2g
    memswap_limit: 2g
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1024
    networks:
      - cognitia-network

networks:
  cognitia-network:
    driver: bridge
