name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy docker-compose to server
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no docker-compose.yml seed@${{ secrets.VM_IP }}:/home/seed/Cognitia/Cognitia-Backend/

      - name: SSH and deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no seed@${{ secrets.VM_IP }} << 'EOF'
            cd /home/seed/Cognitia/Cognitia-Backend
            docker-compose up -d --force-recreate app
          EOF
