name: Test, Build and Deploy to Azure VM via SSH with Docker

on:
  push:
    branches:
      - master

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t cognitia-backend:latest .

      - name: Save Docker image as tarball
        run: docker save cognitia-backend:latest -o cognitia-backend.tar

      - name: Copy Docker image to remote server
        run: |
          scp -o StrictHostKeyChecking=no cognitia-backend.tar seed@${{ secrets.VM_IP }}:/home/seed/

      - name: Copy docker-compose.yml to remote server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml seed@${{ secrets.VM_IP }}:/home/seed/Cognitia/Cognitia-Backend/

      - name: Deploy Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no seed@${{ secrets.VM_IP }} << 'EOF'
            docker load -i /home/seed/cognitia-backend.tar
            cd /home/seed/Cognitia/Cognitia-Backend
            docker-compose up -d --force-recreate app
          EOF
          scp -o StrictHostKeyChecking=no docker-compose.yml seed@${{ secrets.VM_IP }}:/home/seed/Cognitia/Cognitia-Backend/

      - name: Deploy via SSH with Docker-Compose
        run: |
          ssh -o StrictHostKeyChecking=no seed@${{ secrets.VM_IP }} << 'EOF'
            cd /home/seed/Cognitia/Cognitia-Backend
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cognitia-backend:latest
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cognitia-backend:latest cognitia-backend:latest
            docker-compose up -d --force-recreate app
          EOF
