name: Test, Build and Deploy Backend to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t cognitia-backend:latest .

      - name: Save Docker image to tar
        run: docker save cognitia-backend:latest -o cognitia-backend.tar

      - name: Write SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy files to server (image + docker-compose)
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no cognitia-backend.tar seed@${{ secrets.VM_IP }}:/home/seed/
          scp -i key.pem -o StrictHostKeyChecking=no docker-compose.yml seed@${{ secrets.VM_IP }}:/home/seed/Cognitia/Cognitia-Backend/

      - name: SSH and deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no seed@${{ secrets.VM_IP }} << 'EOF'
            cd /home/seed/Cognitia/Cognitia-Backend
            docker load -i /home/seed/cognitia-backend.tar
            docker-compose down
            docker-compose up -d --force-recreate app
          EOF
